spring:
  application:
    name: prova-rems-soft

  datasource:
    url: jdbc:postgresql://localhost:5432/prova-rems
    username: postgres
    password: totvs
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: mySuperSecretKey
